---
title: "College Cost Analysis"
author: "Emmanuel Laureano-Maravilla"
format: html
---

##Research Question:
-How does college tuition varies in the United States?

##Data Source Description:
This dataset for this project it going to be from the U.S department Education College Scorecard database. The dataset contains institution level information on college all through the U.S.

##Variables:
INSTNM: Institution name
CONTROL: Type of Institution
TUITIONFEE_IN: Tuition in state
TUITIONFEE_OUT: Tuition out of state
STABBR: State 
UGDS: number of undergraduates 

##Data Visualization
The final product visualization will include a histogram graph. The histogram graph will show the distribution of average tuition in United States. 

The visualization will show the trends in tuition over time and the difference in private and public. It will be labeled clearly and add different colors to the different categories.

I think it will be better if the variables were to be cleaner and new variables possibly to show avg tuition. 

##Data cleaning

Reformat Variables - Yes, some names need to become clearer

Create New Variables- Yes, I will create new variables called avg tuition by combining both in and out of state tuition. For example, to combine both tuitions it will be (TUITIONFEE_IN + TUITIONFEE_OUT)/2

Filter Data- Yes, I will need to keep the important variables that relate to data like tuition, institution type, and possibly enrollement. It will condense the data and make it easier to look at.

Group data - I will group that data by year and institution type to analyze how tuition changes over time and prepare to visualization 




```{r, echo=FALSE}
library(tidyverse)

college <- read_csv("Most-Recent-Cohorts-Institution.csv")

college_clean |>
  group_by(STABBR) |>
  summarize(median_tuition = median(avg_tuition, na.rm = TRUE)) |>
    
    ggplot(aes(x = reorder(STABBR, median_tuition), y = median_tuition)) +
      geom_col() +
    coord_flip() +
      labs(
        title = "Average College Tuition By State",
        x = "State", 
        y = "Average Tuition"
      )
```
This is a rough draft of a bar chart showing the average college tuition across colleges. I cleaned data by removing missing values and created a new variable called avg tuition. It combines in and out of state tuition. This visualization shows how tuition varies depending on location of the institutions.



